### ISSUE TITLE
New sim checklist

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#2]
# New Repository Checklist

These steps contain the following placeholders that you'll need to fill in:

- `{{AUTHOR}}}` - the name that will appear in `@author` code annotations, e.g. `Jane Doe`
- `{{REPO}}` - the repository name, e.g. `gas-properties`. This should be composed of lower-case characters and dashes, and should have <=214 characters (see naming constraints in https://docs.npmjs.com/cli/v7/configuring-npm/package-json).
- `{{TITLE}}` - the simulation's title, e.g. `Gas Properties`

## Steps to create a new simulation repo

At https://github.com/phetsims:
- [x] Press the "New" button.
- [x] Set the Description field to `"{{TITLE}}" is an educational simulation in HTML5, by PhET Interactive Simulations.`
- [x] Set visibility to "Public".
- [x] DO NOT check the "Initialize this repository with a README" checkbox.
- [x] Leave "Add .gitignore" set to "None"
- [x] Leave "Add a license" set to "None".

In your working copy of perennial repo:
- [x] Run `grunt create-sim --repo="{{REPO}}" --author="{{AUTHOR}}" --title="{{TITLE}}"` to create the file structure and skeleton code for the sim.

In your working copy of the sim repo:
- [x] `git init`
- [x] `git add * .gitignore`
- [x] `git commit -m "Initial commit"`
- [x] `git remote add origin https://github.com/phetsims/{{REPO}}.git`
- [x] `git push -u origin master`

At https://github.com/phetsims/{{REPO}}:
- [x] Go to Settings => Collaborators and teams, then "Add teams". See [team assignment.md](https://github.com/phetsims/phet-info/blob/master/policies/team%20assignment.md) for assignments by repo type.
- [x] Create a Sim Checklist issue using template [sim_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/sim_checklist.md). Use "{{TITLE}} Master Checklist" as the issue name. Assign to @ariel-phet.

In your working copy of perennial repo:
- [x] Add the new repo to `perennial/data/active-repos`. Commit and push. Then pull perennial-alias so these two checkouts stay in sync. If needed immediately, run `cd perennial/ && grunt generate-data` and commit and push to update data lists. Otherwise it is done every night as part of daily grunt work.

Other:
- [x] Navigate to https://bayes.colorado.edu/dev/phettest/ and click the "Refresh Perennial" button. If you do not know the password, please ask another developer.
- [x] Apply GitHub labels. See [github-labels/README.md](https://github.com/phetsims/phet-info/blob/master/github-labels/README.md).
- [x] Apply branch protection rules. Use [This script to do so](https://github.com/phetsims/perennial/blob/master/js/scripts/protect-branches-for-repo.js).
- [x] Notify Slack channel dev-public that the repo has been created. E.g. "I just added a new repository, {{REPO}}. Please pull perennial and perennial-alias and run `clone-missing-repos.sh` at your convenience."
- [x] If using IDEA/Webstorm (pre-2018), add the git source root for the repository.
- [x] Follow any remaining "Implementation" tasks in the Master Checklist issue that you created above.
- [x] If applicable, add any needed dependencies to `phetLibs` in package.json. If you change package.json, run `grunt update`.
- [x] Add the sim to [responsible_dev.json](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.json).
- [x] Add the sim to chipper/tsconfig/all/tsconfig.json

**Comment by chrisklus** [comment]
Sim setup is complete. Sprint development is continuing over in #6. Closing.
