### ISSUE TITLE
Update the colors

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#47]
From February 16th design meeting:

>Need hex codes for colors
>When color editor is ready, AM can finalize colors

@amanda-phet the colors have been added to the color profile over in https://github.com/phetsims/center-and-spread/issues/35

Here is the link for adjusting these on phettest:
https://bayes.colorado.edu/dev/phettest/phetmarks/color-editor.html?sim=center-and-spread&brand=phet

Please assign back to @samreid and me when you have a list of colors for those color names.

**Comment by amanda-phet** [comment]
- [ ] To improve contrast with the grass and sky, the arrows in the play area for mean and median, as well as the predict mean/median markers, will need a thin black stroke around them. I'll make a separate issue for this since it will relate to the arrow design as a whole. 
- [ ] For the sky gradient, I thought there was a standard "PhET sky gradient" pattern. I looked at Projectile Motion and that sky seems similar to other sims, and it only uses two colors in the gradient. Can we match that sky? The sky gradient in Center and Spread seems to have three colors, but I'd like to just match the sky that is in other PhET sims if possible. Projectile Motion seems like a reasonable sky to match.
- [ ] `centerAndSpread.medianColor` #F03000
- [ ] `centerAndSpread.meanColor` #8500BD
- [ ] `centerAndSpread.groundColor` #009245
- [ ] `centerAndSpread.dragIndicatorColor` #6BC6FF
- [ ] `centerAndSpread.medianQuestionBarFill` #58C662
- [ ] `centerAndSpread.meanAndMedianQuestionBarFill` #955fC4
- [ ] `centerAndSpread.spreadQuestionBarFill` #FDD10B

**Comment by chrisklus** [comment]
I added all the colors and switched the sky gradient to two colors (from Projectile Motion). @amanda-phet those were just hard coded for that sim, and I think they look pretty saturated for CAS. Let me know what you think.

**Comment by chrisklus** [comment]
In discussion with @samreid and @amanda-phet, we decided to revert to the 3 color gradient and then lightened those colors a bit. Closing.
